### PR TITLE
Change bnftp to exit success when successful

### PR DESCRIPTION
**Pull request by carlbennett**

### CODE REVIEW

**Comment by carlbennett** [comment]
Build failed because of an unrelated zlib error in the `develop` branch of `pvpgn/pvpgn-server`.

**Comment by carlbennett** [comment]
@cen1 Any chance we could get this merged?

**Comment by cen1** [comment]
Yeah, can you just properly rebase so it looks like a single commit merge not an 8 commit merge? Or just open a new clean pull, I can merge it asap.

**Comment by carlbennett** [comment]
#394

**Pull request closed without merging**
