### PR TITLE
Support for W3 patch 1.27a

### PR DESCRIPTION
**Pull request by cen1**
This add the proper versioncheck configuration, new mpq file and necessary cmake changes for W3 1.27a.

### CODE REVIEW

**Comment by xboi209** [comment]
Can you also add a versioncheck entry for WarCraft 3: Reign of Chaos 1.27a as well.

**Comment by cen1** [comment]
Ok, will do it this weekend.

**Comment by cen1** [comment]
It appears that RoC client also sends clienttag=W3XP (SID_AUTH_INFO) so pvpgn chooses W3XP entry as a match and I can connect normally with RoC on the same versioncheck entry. Even after adding a slightly modified entry for RoC it still chose TFT because clienttag sent by RoC client says W3XP. it also sends W3XP on official. Don't ask me why but apparently it "just works".

**Comment by xboi209** [comment]
Still need to check if the clienttag is still shown as W3XP when the expansion isn't installed and another versioncheck entry for macs. Will accept this for now.

**Pull request merged**
