### PR TITLE
Created Dockerfile and supporting files

### PR DESCRIPTION
**Pull request by stickmansgallows**
I made a simple docker container about a year ago and I just copied it over.
#268

### CODE REVIEW

**Comment by HarpyWar** [comment]
Don't docker container have to be published on https://hub.docker.com but not here?

**Comment by cen1** [comment]
Docker file and scripts being part of this git is fine. I think it needs to be prepped for mysql/postgres and perhaps do some init (create an admin user with full CG etc).

**Comment by stickmansgallows** [comment]
Dockerfiles can be hosted in git and then the hub.docker.com repo can pull the dockerfile. It can also automatically build a new docker image when changes are made to git.
I'll look into mysql and admin stuff this weekend.

**Comment by Jordan-Gillard** [comment]
RIP this pull request

**Comment by cen1** [comment]
Without added support to load config via env such docker container provides only little benefit.

**Comment by Kelwing** [comment]
The container should be a multi-stage build, not all in one stage.  This needs a lot of work before it should be considered ready for merge.

**Pull request closed without merging**
